spring:
 application:
  name: OnlineShop
 datasource:
  driver-class-name: "com.mysql.cj.jdbc.Driver"
  url: "jdbc:mysql://localhost:3306/onlineshop"
  username: root
  password: I~992kqo
 h2:
  console:
   enabled: true
   path: /h2-console
 jpa: 
  show-sql: true
  defer-datasource-initialization: true
  hibernate:
  ddl-auto: none
server:
 port: 8080
logging:
 level:
  org.springframework: DEBUG